### ISSUE TITLE
Does this plugin work with custom gocd task plugins?

### ISSUE THREAD

**Issue by dlethin** [gocd-contrib/gocd-groovy-dsl-config-plugin#114]
I'm just getting started with this plugin and trying to run a local validation on my groovy script for generating pipelines.  The script was generated by running an export of an existing pipeline in GoCD.    The job in my pipeline uses the custom script executor task seen [here](https://github.com/gocd-contrib/script-executor-task).

My script looks like this:

```
GoCD.script {
  pipelines {
    pipeline('sample') {
      group = 'sample'
      labelTemplate = '${COUNT}'
      lockBehavior = 'none'
      materials {
        git {
          branch = 'master'
          destination = 'tf'
          shallowClone = false
          url = '<PATH_TO_MY_REPO_REDACTED>'
        }
      }
      stages {
        stage('check') {
          artifactCleanupProhibited = false
          cleanWorkingDir = false
          fetchMaterials = true
          approval {
          }
          jobs {
            job("check") {
              elasticProfileId = 'my-profile'
              runInstanceCount = 1
              timeout = 0
              tasks {
                plugin {
                  options = [
                    script: 'echo hello',
                    shtype: 'bash',
                  ]
                  runIf = 'passed'
                  configuration {
                    id = 'script-executor'
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

However, when I run the validation an output the generated json, the actual task of the job is missing:

```
$ java -jar gocd-groovy-dsl-config-plugin-0.7.9-118.jar syntax -j sample.groovy
Parsing file sample.groovy. Ok!Oct 30, 2019 2:08:05 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.0.17.Final
 Found environments: [].
 Found pipelines: [sample].

Showing JSON from file sample.groovy:
{
  "target_version" : 7,
  "pipelines" : [ {
    "name" : "sample",
    "group" : "sample",
    "display_order_weight" : -1,
    "label_template" : "${COUNT}",
    "lock_behavior" : "none",
    "materials" : [ {
      "type" : "git",
      "destination" : "tf",
      "auto_update" : true,
      "url" : "<PATH_TO_MY_REPO_REDACTED>",
      "branch" : "master",
      "shallow_clone" : false
    } ],
    "stages" : [ {
      "name" : "check",
      "fetch_materials" : true,
      "clean_working_directory" : false,
      "never_cleanup_artifacts" : false,
      "approval" : {
        "type" : "success"
      },
      "jobs" : [ {
        "name" : "check",
        "run_instance_count" : 1,
        "timeout" : 0,
        "elastic_profile_id" : "my-profile"
      } ]
    } ]
  } ]
}
```

Should this work?   Am I doing something wrong?   Thanks.

**Comment by ketan** [comment]
Looks like a big. I'll take a look today.

**Comment by ketan** [comment]
As an aside: this may be more readable https://javadoc.io/static/com.github.ketan/dsl/0.7.4-60/cd/go/contrib/plugins/configrepo/groovy/dsl/Tasks.html#bash-groovy.lang.Closure-

**Comment by ketan** [comment]
I've pushed out a fix, and a release as well. Let me know if that works for you.

**Comment by dlethin** [comment]
I tested out the change, and  it at works via local validation. I now get:

```
      "jobs" : [ {
        "name" : "check",
        "run_instance_count" : 1,
        "timeout" : 0,
        "elastic_profile_id" : "my-profile",
        "tasks" : [ {
          "type" : "plugin",
          "run_if" : "passed",
          "plugin_configuration" : {
            "id" : "script-executor",
            "version" : "1"
          },
          "configuration" : [ {
            "key" : "script",
            "value" : "echo hello"
          }, {
            "key" : "shtype",
            "value" : "bash"
          } ]
        } ]
```

I'll try to commit my pipeline and confirm it works with GoCD itself sometime in the next 2 business days, but I'm assuming its going to work.  Thanks for the quick turnaround time.

BTW, I'm not really sure I understand your comment above - https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/issues/114#issuecomment-548176438

Was that mean for me?  Cheers.
```

**Comment by arvindsv** [comment]
@dlethin I think @ketan was saying that it might be cleaner / simpler to use `bash` + `commandString` as shown in [the example](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin#example).

However, your issue did show a bug which had to be fixed. :)

**Comment by dlethin** [comment]
@arvindsv @ketan    Ah -- I understand now.   Thanks. My example was a bit stripped down to a single line bash command to demonstrate the issue I was facing.  In reality my script is several lines long and in those situations we find it much easier to use the script executor plugin for that, rather than try to break it down into multiple bash task command executions.  This has especially been true as its cumbersome doing this through the UI -- for example if you need to add another task somewhere other than the last one. Maybe if we move to groovy templates for these pipelines that's less of a concern.  Another future thought altogether would be to consider committing the script into a repo and just invoking it through GoCD.

Cheers.

**Comment by ketan** [comment]
Committing the script to source control and call that instead of putting in big blobs of "scripts" in the config is something we strongly recommend. That way your pipeline is almost independent of the CI/CD tool you use.

In my personal opinion (not that of the gocd team), I consider task plugins major anti-patterns. IMO: users should just call out to shell scripts instead of relying on task plugin magic for anything.
