### ISSUE TITLE
Why this over yaml/json plugins

### ISSUE THREAD

**Issue by MPV** [gocd-contrib/gocd-groovy-dsl-config-plugin#215]
I'm trying to gauge why I might want to use this plugin over for example https://github.com/tomzo/gocd-yaml-config-plugin

Would it make sense to offer a list of supported features in the README, or even a comparison between current versions? Or maybe just a sentence about the philosophical differences (apart from which language it's defined in).

**Comment by MPV** [comment]
Ah, i just discovered this helpful comment:
https://github.com/gocd/gocd/issues/6123#issuecomment-697314550

**Comment by marques-work** [comment]
@MPV yep, basically you will have the full power of a programming language to do complex things (like templating, conditional logic, etc) when building your pipelines. And, as you've linked, now it has first-class pull request and notification/build status support built-in.

Of course, I'd want to get some of this backported into the YAML/JSON plugins, but it's going to take a lot of thought on how to model the DSL concepts here in YAML/JSON. Not to mention a lot of work getting the plumbing working.

**Comment by marques-work** [comment]
Closing this issue; open a new issue if you still have questions.
