### ISSUE TITLE
Support templates as code (in addition to pipelines as code)

### ISSUE THREAD

**Issue by MPV** [gocd-contrib/gocd-groovy-dsl-config-plugin#216]
It would be nice being able to define both pipelines and their templates using code. 

Would this plugin be a suitable component where to implement this?

**Comment by arvindsv** [comment]
Not really. This is more a consequence of how templates work in GoCD.

See: https://github.com/tomzo/gocd-yaml-config-plugin/issues/132 and https://github.com/tomzo/gocd-yaml-config-plugin/issues/2

**Comment by MPV** [comment]
Alright. 👍 Thanks for the enlightenment. Will close this for now then.
