### ISSUE TITLE
Is there an example I am not seeing that shows how to trigger a pipeline from the completion of another ?

### ISSUE THREAD

**Issue by camechis** [gocd-contrib/gocd-groovy-dsl-config-plugin#29]

**Comment by marques-work** [comment]
@camechis sorry for the really late answer, but to do this, one just needs to add the upstream pipeline as a material of the downstream pipeline.

Here's an example from our own main pipeline definitions:

https://github.com/gocd/pr-pipelines-workflow/blob/59defd4a5167627504f175264fe88629d176c861/.gocd/build.gocd.groovy#L145-L148
