### ISSUE TITLE
fetchArtifact closure requires pipeline field to be supplied

### ISSUE THREAD

**Issue by dlethin** [gocd-contrib/gocd-groovy-dsl-config-plugin#314]
Thanks for the great plugin.

I ran into an issue using this groovy DSL to when attempting to define pipeline  where a task within a second stage job fetches artifacts from a job in a previous stage.  According to the GoCD [reference](https://docs.gocd.org/current/configuration/configuration_reference.html) under `<fetchartifact>`, this can be achieved by leaving the pipeline field empty.

However according to the source code in the DSL, the field is annotated with `    @NotEmpty` and the validator tool fails the script

An example DSL script:

```
import cd.go.contrib.plugins.configrepo.groovy.dsl.*

GoCD.script {
  pipelines {
    pipeline('multistage-pipeline') {
      group = "mygroup"
      materials {
        git {
          url = 'https://github.com/project/path'
          branch = 'develop'
        }
      }

      stages {
        stage('first') {
          jobs {
            job("producer") {
              tasks {
                bash {
                  commandString = "./run-me.sh"
                }
              }
              artifacts {
                build {
                  source = 'build'
                }
              }
            }
          }
        }

        stage('second') {
          jobs {
            job('consumer') {
              tasks {
                fetchArtifact {
                  destination = "build"
                  file = false
                  job = "producer"
                  stage = "first"
                  // pipeline = "must-not-be-empty"
                  source = 'build'
                }
              }
            }
          }
        }
      }
    }
  }
}

```

produces these errors:

```
java -jar gocd-groovy-dsl-config-plugin-2.0.0-1.jar syntax -j demo.groovy
Parsing file demo.groovy. Ok!Jan 23, 2022 11:40:35 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.2.0.Final
Found 16 validation errors!
  - pipelines[0].stages[1].jobs.elements[0].tasks.elements[0].pipeline must not be empty
  - pipelines[0].stages.elements[1].jobs.elements[0].tasks.elements[0].pipeline must not be empty
  - pipelines[0].stages[1].jobs.elements[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages.elements[1].jobs.elements[0].tasks.elements[0].pipeline must not be empty
  - pipelines.elements[0].stages.elements[1].jobs.elements[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages.elements[1].jobs[0].tasks[0].pipeline must not be empty
  - pipelines[0].stages.elements[1].jobs.elements[0].tasks[0].pipeline must not be empty
  - pipelines[0].stages[1].jobs[0].tasks.elements[0].pipeline must not be empty
  - pipelines[0].stages.elements[1].jobs[0].tasks.elements[0].pipeline must not be empty
  - pipelines[0].stages.elements[1].jobs[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages.elements[1].jobs[0].tasks.elements[0].pipeline must not be empty
  - pipelines[0].stages[1].jobs[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages[1].jobs[0].tasks.elements[0].pipeline must not be empty
  - pipelines.elements[0].stages[1].jobs[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages[1].jobs.elements[0].tasks[0].pipeline must not be empty
  - pipelines.elements[0].stages[1].jobs.elements[0].tasks.elements[0].pipeline must not be empty
░▒▓ ~/bld/simplisafe/ceng-gocd-pipelines  main !2 ?1 ▓▒░
```

uncomment the commented out pipeline, run again and it works, not complaining that there actually is no upstream pipeline material with that name...

```
Parsing file demo.groovy. Ok!Jan 23, 2022 11:43:58 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 6.2.0.Final
 Found environments: [].
 Found pipelines: [multistage-pipeline].

Showing JSON from file demo.groovy:

{
  "target_version" : 7,
  "pipelines" : [ {
    "name" : "multistage-pipeline",
    "group" : "mygroup",
    "display_order_weight" : -1,
    "materials" : [ {
      "type" : "git",
      "auto_update" : true,
      "url" : "https://github.com/project/path",
      "branch" : "develop"
    } ],
    "stages" : [ {
      "name" : "first",
      "jobs" : [ {
        "name" : "producer",
        "artifacts" : [ {
          "type" : "build",
          "source" : "build"
        } ],
        "tasks" : [ {
          "type" : "exec",
          "command" : "bash",
          "arguments" : [ "-c", "./run-me.sh" ]
        } ]
      } ]
    }, {
      "name" : "second",
      "jobs" : [ {
        "name" : "consumer",
        "tasks" : [ {
          "type" : "fetch",
          "artifact_origin" : "gocd",
          "pipeline" : "must-not-be-empty",
          "stage" : "first",
          "job" : "producer",
          "is_source_a_file" : false,
          "source" : "build",
          "destination" : "build"
        } ]
      } ]
    } ]
  } ]
}
```

If I comment out the @NotEmpty annotation here and build a local copy of the validator tool, the pipeline will validate fine.

I can create a PR if its helpful.

Thanks.

Doug Lethin

**Comment by chadlwilson** [comment]
Does the constructed pipeline work correctly if you specify the pipeline name to be the same as the pipeline under construction? (as a workaround)

**Comment by chadlwilson** [comment]
Having had another look, I think some variant of your suggestion would be great and a PR would be welcomed. If you are willing to help me sanity check an experimental release of the plugin (which has not been released for a while) I am motivated to help out :-)

I'm not super familiar with the test automation currently in the code/repo here, but if it can be validated both both an internal artifact and one of the external artifact plugins, that'd be great, as they have a shared definition.

It should be fine as it is [optional in the YAML config plugin](https://github.com/tomzo/gocd-yaml-config-plugin#fetch) already.

**Comment by dlethin** [comment]
Thanks for the response.  Nice to have confidence the YAML config plugin supports the field being optional.    I'm too am not super/familiar with this repo or the test framework.  I'm not even sure what this means:

> but if it can be validated **both an internal artifact and one of the external artifact plugins**

It's been 5 years since I've done any active java/gradle development but recalled enough to try to experiment.

I'll have to try to find some time to learn more if its a matter of contributing a PR with tests.

I'm not actively using this plugin, but wanted to start using it for a particular use case of pipelines I didn't want to hand code.    I had run into some problems I didn't fully understand when trying to use the plugin directly in our GoCD server.   I took a *short* cut where I use this tools linter to create the json representation of the pipelines and then commit those pipelines to my config repo.  I hope to circle back and troubleshoot when I have some slack in schedule to make it so I can use the plugin directly.

Cheers.

**Comment by dlethin** [comment]
Thanks so much.  I'll throw in a task to look at this some time this week.

**Comment by chadlwilson** [comment]
I released a proper version of the plugin earlier today as well, so need need to worry about the experimental version: https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v2.1.0-345
