### ISSUE TITLE
Bug: The plugin does not seem to contain plugin.xml or gocd-bundle.xml

### ISSUE THREAD

**Issue by asavchkov** [gocd-contrib/gocd-groovy-dsl-config-plugin#348]
Tried to install dsl-2.1.1-416.jar on the GoCD server Version: 22.2.0 (14697-4bdda4e0d769e66da651926c7066979740bd7ae7). This is the current GoCD version. Got an error:
```
There were errors loading the plugin

Plugin with ID (dsl-2.1.1-416.jar) is not valid. The plugin does not seem to contain plugin.xml or gocd-bundle.xml
```
Looking inside the jar I indeed don't see either plugin.xml or gocd-bundle.xml.

**Comment by chadlwilson** [comment]
That's not the plugin, thats the DSL API jar for people who want code completion to work with locally.

You need to install the one with 'plugin' in the name.
