### ISSUE TITLE
DSL Syntax reference

### ISSUE THREAD

**Issue by asavchkov** [gocd-contrib/gocd-groovy-dsl-config-plugin#351]
Is it possible to provide a complete DSL syntax reference similar to https://github.com/tomzo/gocd-yaml-config-plugin#format-reference?
The plugin is great for generating complex pipelines dynamically but I have troubles to simply find out which keywords are supported, which original XML elements they relate to, which format they should be written in and so on. So instead of guessing and searching in the code and in examples it would be great just to consult a reference guide.

**Comment by chadlwilson** [comment]
I think the idea was that you follow the instructions to set up a mini-project in your IDE and add the DSL to do so, so you can rely on code completion/suggestions rather than being documentation driven. 

I'm sure that has some gaps, but wonder if you've tried working in that way?

**Comment by asavchkov** [comment]
No, I don't use an IDE, just a text editor with usual features like syntax highlighting, collapse/expand nodes etc. So having a simple doc at hand would be quite useful.

**Comment by chadlwilson** [comment]
While I'm not the original main author here, it doesn't seem like that usage flow is really consistent with the design goal of having a full scripting language based plugin, as opposed to the JSON or YAML earlier options. Unless you, say, constantly run validating off a terminal side by side with your editor to get faster feedback.

The DSL is fully documented via Javadocs which you can download at https://repo1.maven.org/maven2/cd/go/groovydsl/dsl/2.1.1-416/dsl-2.1.1-416-javadoc.jar - if you don't want to use an IDE to assist with displaying the docs inline alongside auto-completions, suggest you download that, unzip it and open it in a browser.

**Comment by asavchkov** [comment]
Thank you very much for the javadoc, looks like it's more or less the specification I had in mind opening this issue.

**Comment by chadlwilson** [comment]
I'll try and add something to the README if I remember 😰
