### ISSUE TITLE
Error when perform offline syntax check

### ISSUE THREAD

**Issue by anhle1-tw** [gocd-contrib/gocd-groovy-dsl-config-plugin#372]
When I run 
`java -jar gocd-groovy-dsl-config-plugin-2.1.2-446.jar syntax github-hello.groovy
` 
I see this error:

Bad!
java.lang.NoClassDefFoundError: com/thoughtworks/go/plugin/api/logging/Logger
    at cd.go.contrib.plugins.configrepo.groovy.resolvers.Notifications.<clinit>(Notifications.java:46)

**Comment by chadlwilson** [comment]
Should be fixed in https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v2.1.3-467
