### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by videocursoscloud** [gocd-contrib/gocd-groovy-dsl-config-plugin#61]
Hi,

I´m using this plugin with the example code and i get this error.

1. 'target_version' is 4 but the GoCD Server supports 3

Does this means that the plugin does not support yet gocd server version 4?

**Comment by arvindsv** [comment]
@videocursoscloud Which release of GoCD server are you using? You'll need to be using GoCD 19.3.0 for release 0.7.5-66 of this plugin.

@ketan Maybe we can mention that in the [release notes](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v0.7.5-66)?

**Comment by arvindsv** [comment]
At least that's how I'm interpreting [this change](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/commit/9b7fefd557f0ec6a230175a1f003a491955f659f#diff-5e8d8bbb87aea2b672f7edee62b0c687R50).

**Comment by videocursoscloud** [comment]
I´m using GoCD Version: 19.2.0 .

Can i use maybe a previous release for this version?

**Comment by arvindsv** [comment]
Yes, the previous version (https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v0.7.4-65) should work fine. Please try that.

**Comment by videocursoscloud** [comment]
I updated gocd to the latest version and now it works. Thanks for the help.
