### ISSUE TITLE
Allow overriding Groovy sandbox whitelist/blacklist

### ISSUE THREAD

**Issue by m13t** [gocd-contrib/gocd-groovy-dsl-config-plugin#63]
Hi

Is it possible to request the ability to override the Blacklist and Whitelist for the Groovy sandbox?

I would like to be able to access environment variables set on the GoCD server in order to conditionally define or otherwise change the behaviour of pipelines across different instances of GoCD servers (test and production). Currently it seems that System.getenv is blacklisted and there's no option to modify this short of forking the repo.

Alternatively, if there's some other way to pass in information so that it is available to the Groovy script that would be great.

Thanks

**Comment by arvindsv** [comment]
@ketan Wouldn't this just be configuration at the plugin side? Are you saying GoCD server needs to do beyond the "Get Plugin Configuration" call?

**Comment by ketan** [comment]
> @ketan Wouldn't this just be configuration at the plugin side? Are you saying that GoCD server needs to do something beyond the ["Get Plugin Configuration"](https://plugin-api.gocd.org/current/config-repo/#get-plugin-configuration) call?

Yes. "Get config repo configuration" call is what we need at this point.

**Comment by ketan** [comment]
While we discuss possible ways to overcome the sandbox, would you be OK with disabling the sandbox completely (using a some way to toggle it)

**Comment by m13t** [comment]
We've worked round this issue until a proper solution is in place by making the following changes to the `GroovyScriptRunner.java` file.

```diff
diff --git a/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/GroovyScriptRunner.java b/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/GroovyScriptRunner.java
index befbc1a56cc2311772b1b60a096dfc4ff8f444d6..ebd9fd924cf12e407262a761e23af21b6dc2d83c 100644
--- a/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/GroovyScriptRunner.java
+++ b/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/GroovyScriptRunner.java
@@ -29,10 +29,13 @@ import org.codehaus.groovy.control.customizers.ImportCustomizer;
 import org.codehaus.groovy.runtime.ResourceGroovyMethods;
 
 import java.io.File;
+import java.util.Map;
 import java.io.IOException;
 
 public class GroovyScriptRunner {
 
+    public static final String CUSTOM_ENV_PREFIX = "GO_GROOVY_VAR_";
+
     private final CompilerConfiguration compilerConfiguration;
 
     private final GroovyShell groovyShell;
@@ -47,7 +50,18 @@ public class GroovyScriptRunner {
         compilerConfiguration.addCompilationCustomizers(importCustomizer);
 
         ClassLoader secureClassLoader = GroovySandbox.createSecureClassLoader(GroovyScriptRunner.class.getClassLoader());
-        this.groovyShell = new GroovyShell(secureClassLoader, new Binding(), compilerConfiguration);
+        Binding binding = new Binding();
+
+        for (Map.Entry<String, String> item : System.getenv().entrySet()) {
+            if (item.getKey().startsWith(CUSTOM_ENV_PREFIX)) {
+                String propName = item.getKey().substring(13).toLowerCase();
+                String propVal = item.getValue();
+
+                binding.setProperty(propName, propVal);
+            }
+        }
+
+        this.groovyShell = new GroovyShell(secureClassLoader, binding, compilerConfiguration);
     }
 
     public Object runScript(String fileName) throws IOException, ResourceException, ScriptException {
```

This isn't ideal but does allow us to make certain external variables available within the Sandbox without exposing the entire environment.

**Comment by ketan** [comment]
Hmm. Interesting.

I think providing a system property, which allows users to point to an additional [whitelist file](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/blob/master/sandbox/src/main/resources/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/generic-whitelist), with [these lines](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/blob/master/sandbox/src/main/resources/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/blacklist#L58-L59), will actually allow you to do what you're trying to do, the user provided whitelist would have to be [loaded here](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/blob/master/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/GenericWhitelist.java#L35). This is untested code, but I think you get the idea:

```patch
diff --git a/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/GenericWhitelist.java b/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/GenericWhitelist.java
index 7c87c49..191544b 100644
--- a/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/GenericWhitelist.java
+++ b/sandbox/src/main/java/cd/go/contrib/plugins/configrepo/groovy/sandbox/whitelists/GenericWhitelist.java
@@ -24,7 +24,11 @@

 package cd.go.contrib.plugins.configrepo.groovy.sandbox.whitelists;

+import org.apache.commons.lang3.StringUtils;
+
+import java.io.File;
 import java.io.IOException;
+import java.util.ArrayList;

 /**
  * Includes entries useful for general kinds of scripts.
@@ -32,7 +36,17 @@ import java.io.IOException;
 public final class GenericWhitelist extends ProxyWhitelist {

     public GenericWhitelist() throws IOException {
-        super(StaticWhitelist.from(GenericWhitelist.class.getResource("generic-whitelist")));
+        super(whitelists());
+    }
+
+    private static Whitelist[] whitelists() throws IOException {
+        ArrayList<Whitelist> whitelists = new ArrayList<>();
+        whitelists.add(StaticWhitelist.from(GenericWhitelist.class.getResource("generic-whitelist")));
+        String property = System.getProperties().getProperty("some-property");
+        if (StringUtils.isNotBlank(property)) {
+            whitelists.add(StaticWhitelist.from(new File(property).toURI().toURL()));
+        }
+        return whitelists.toArray(new Whitelist[]{});
     }

 }
```

it might be nifty to allow a whitelist per config repo.

**Comment by m13t** [comment]
I guess we may have further requirements to extend the whitelist depending on other support that may come (which I mentioned in my other ticket regarding sharing files). However, the initial blocker for us was not being able to have the groovy code evaluate differently depending on which instance of our GoCD master the code was running on.

For the time being, the code I posted above fulfils this without compromising the security, which even with a custom whitelist and allowing System.GetEnv to be called, is more open than we need.

**Comment by arvindsv** [comment]
> Yes. "Get config repo configuration" call is what we need at this point.

@ketan Actually, there is config-repo level settings passed in as a part of the request to `parseDirectory`: https://plugin-api.gocd.org/current/config-repo/#parse-directory

**Comment by marques-work** [comment]
No more sandbox as of 2.x release; closing this as it is moot now.
