### ISSUE TITLE
Possible To Span Multiple Files?

### ISSUE THREAD

**Issue by m13t** [gocd-contrib/gocd-groovy-dsl-config-plugin#65]
Hi,

Wondering if it's possible for code to span multiple groovy files, or is each file evaluated in isolation?

I'm thinking it would be good to offload some repetitive functions into a single file and be able to reference those functions from other files.

**Comment by ketan** [comment]
See #63. Until that is fixed, I don't think it's currently possible to "share code". I can possibly add a feature that disables the sandbox (which you can do with repos where you trust what goes in).

**Comment by m13t** [comment]
Ah so this is also related to my other issue then? I did see that the sandbox code runs each file independently so I assumed this was the case for sharing code amongst files. Wasn't sure it was related to the sandboxed methods though.

**Comment by marques-work** [comment]
As of the 2.x release, there is no more sandbox. Theoretically, you should be able to load trusted files.

**Comment by marques-work** [comment]
Closing this for now, but if you aren't able to get this working now that the sandbox is gone you can reopen this and report what happened.
